#!/bin/bash

# Check if python3 is installed
if ! command -v python3 &>/dev/null; then
    echo "python3 not found. Attempting to install..."
    sudo apt-get update
    sudo apt-get install python3
fi

# Check if pip3 is installed
if ! command -v pip3 &>/dev/null; then
    echo "pip3 not found. Attempting to install..."
    sudo apt-get update
    sudo apt-get install python3-pip
fi


# Check if python3-tk is installed
if ! command -v python3-tk &>/dev/null; then
    echo "python3-tk not found. Attempting to install..."
    sudo apt-get update
    sudo apt-get install python3-tk
fi

# Check if python3-dev is installed
if ! command -v python3-dev &>/dev/null; then
    echo "python3-dev not found. Attempting to install..."
    sudo apt-get update
    sudo apt-get install python3-dev
fi



# List of python dependencies
declare -a arr=("requests" "pywhatkit" "pillow" "transformers" "torch")
pip install art
for i in "${arr[@]}"
do
    pip_dependency=$(pip3 list | grep $i)
    if [ -z "$pip_dependency" ]; then
        echo "The $i module is not installed. Attempting to install..."
        pip3 install $i
    else
        echo ""
    fi
done

# Change into the ~/myriadclient/ directory
cd $HOME/myriadclient

python3 myriad-cli.py

